Repository Jordyrat/Rat-ons, pull requests merged in 2024-10, with the labels that each got.

#21 Feature: Relic Spawn Timer
  gradle.properties
  src/main/kotlin/com/ratons/Ratons.kt
  src/main/kotlin/com/ratons/config/features/instances/InstancesConfig.java
  src/main/kotlin/com/ratons/config/features/instances/dungeons/DungeonsConfig.java
  src/main/kotlin/com/ratons/data/KuudraAPI.kt
  src/main/kotlin/com/ratons/data/PacketData.kt
  src/main/kotlin/com/ratons/events/ServerTickEvent.kt
  src/main/kotlin/com/ratons/features/instances/dungeons/RelicSpawnTimer.kt
  src/main/kotlin/com/ratons/utils/RatUtils.kt
Labels: feature

#25 Fix: Semantic Version
  src/main/kotlin/com/ratons/Ratons.kt
  src/main/kotlin/com/ratons/commands/Commands.kt
  src/main/kotlin/com/ratons/features/misc/update/SemanticVersion.kt
  src/main/kotlin/com/ratons/features/misc/update/UpdateManager.kt
Labels: bug

#28 Backend: Introduces auto-labeller
  .github/release-drafter.yml
  .github/workflows/labeller.yml
Labels: backend

#29 Update readme
  README.md
Labels: documentation

#31 Merge conflict labeller
  .github/workflows/label-merge-conflicts.yml
Labels: backend

#30 Party size display
  src/main/kotlin/com/ratons/Ratons.kt
  src/main/kotlin/com/ratons/config/features/instances/InstancesConfig.java
  src/main/kotlin/com/ratons/config/features/instances/PartyFinderConfig.java
  src/main/kotlin/com/ratons/features/instances/PartyFinderFeatures.kt
Labels: feature

#32 Item data display
  src/main/kotlin/com/ratons/Ratons.kt
  src/main/kotlin/com/ratons/config/features/Features.java
  src/main/kotlin/com/ratons/config/features/misc/MiscConfig.java
  src/main/kotlin/com/ratons/features/misc/ItemDataDisplay.kt
  src/main/kotlin/com/ratons/utils/ItemUtils.kt
  src/main/kotlin/com/ratons/utils/RatUtils.kt
  src/main/kotlin/com/ratons/utils/TimeUtils.kt
Labels: feature
